version: "3.8"
services:
  db:
    container_name: postgres_container
    image: postgres
    restart: always
    env_file: 
      - .env
    volumes:
      - ./data:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432